module.exports.SUITES_DIC = {
    spade: "♠",
    club: "♣",
    diamond: "♦",
    heart: "♥"
  };

module.exports.RANKING_DIC = {
    daihugou: "大富豪",
    hugou: "富豪",
    heimin: "平民",
    hinmin: "貧民",
    daihinmin: "大貧民"
  };

module.exports.ERROR_DIC = {
    diffNumOfCards: "カードの枚数は合わせてください。",
    diffSuitCards: "スートしばりに合ったカードを出してください。",
    loseCards: "場のカードより強いものを出してください。",
    handError: "役ができていません。",
    fieldNothing: "フィールドにカードがない状態でパスはできません。",
    goOutRoom: "プレイヤーの数が減ったためゲームを中断します。\nゲームをやめる場合はページを再読み込みしてください。",
    roomFull: "この部屋は既に定員に達しています。",
    roomNothing: "この部屋は既に削除されています。別の部屋に参加するか、新規で部屋を作成してください。"
  };

module.exports.LOSE_REASON_DIC = {
    spade3Finish: "スペ3あがりのため、反則負けとなりました。",
    jokerFinish: "ジョーカーあがりのため、反則負けとなりました。",
    card8Finish: "非階段状態での8あがりのため、反則負けとなりました。",
    card3Finish: "革命状態での3あがりのため、反則負けとなりました。",
    card2Finish: "非革命状態での2あがりのため、反則負けとなりました。",
    card11Finish: "11Backあがりのため、反則負けとなりました。",
    fallingOutCity: "都落ちのため、負けとなりました。"
  };

const DISPLAY_IMAGE_ID = {
    spade3: "spade_3",
    spade4: "spade_4",
    spade5: "spade_5",
    spade6: "spade_6",
    spade7: "spade_7",
    spade8: "spade_8",
    spade9: "spade_9",
    spade10: "spade_10",
    spade11: "spade_jack",
    spade12: "spade_queen",
    spade13: "spade_king",
    spade14: "spade_1",
    spade15: "spade_2",
    club3: "club_3",
    club4: "club_4",
    club5: "club_5",
    club6: "club_6",
    club7: "club_7",
    club8: "club_8",
    club9: "club_9",
    club10: "club_10",
    club11: "club_jack",
    club12: "club_queen",
    club13: "club_king",
    club14: "club_1",
    club15: "club_2",
    diamond3: "diamond_3",
    diamond4: "diamond_4",
    diamond5: "diamond_5",
    diamond6: "diamond_6",
    diamond7: "diamond_7",
    diamond8: "diamond_8",
    diamond9: "diamond_9",
    diamond10: "diamond_10",
    diamond11: "diamond_jack",
    diamond12: "diamond_queen",
    diamond13: "diamond_king",
    diamond14: "diamond_1",
    diamond15: "diamond_2",
    heart3: "heart_3",
    heart4: "heart_4",
    heart5: "heart_5",
    heart6: "heart_6",
    heart7: "heart_7",
    heart8: "heart_8",
    heart9: "heart_9",
    heart10: "heart_10",
    heart11: "heart_jack",
    heart12: "heart_queen",
    heart13: "heart_king",
    heart14: "heart_1",
    heart15: "heart_2",
    joker199: "joker_black",
    joker299: "joker_red"
  };

const DISPLAY_DIC = {
    spade3: "♠3",
    spade4: "♠4",
    spade5: "♠5",
    spade6: "♠6",
    spade7: "♠7",
    spade8: "♠8",
    spade9: "♠9",
    spade10: "♠10",
    spade11: "♠J",
    spade12: "♠Q",
    spade13: "♠K",
    spade14: "♠A",
    spade15: "♠2",
    club3: "♧3",
    club4: "♧4",
    club5: "♧5",
    club6: "♧6",
    club7: "♧7",
    club8: "♧8",
    club9: "♧9",
    club10: "♧10",
    club11: "♧J",
    club12: "♧Q",
    club13: "♧K",
    club14: "♧A",
    club15: "♧2",
    diamond3: "♦3",
    diamond4: "♦4",
    diamond5: "♦5",
    diamond6: "♦6",
    diamond7: "♦7",
    diamond8: "♦8",
    diamond9: "♦9",
    diamond10: "♦10",
    diamond11: "♦J",
    diamond12: "♦Q",
    diamond13: "♦K",
    diamond14: "♦A",
    diamond15: "♦2",
    heart3: "♥3",
    heart4: "♥4",
    heart5: "♥5",
    heart6: "♥6",
    heart7: "♥7",
    heart8: "♥8",
    heart9: "♥9",
    heart10: "♥10",
    heart11: "♥J",
    heart12: "♥Q",
    heart13: "♥K",
    heart14: "♥A",
    heart15: "♥2",
    joker199: "JOKER",
    joker299: "JOKER"
  };